= Getting started with Ansible
[source: http://docs.ansible.com/]

== Overview
Ansible is an IT automation tool. It can configure systems, deploy software, and orchestrate more advanced IT tasks such as continuous deployments or zero downtime rolling updates.

Ansible’s main goals are simplicity and ease-of-use. It manages machines over the SSH protocol.

== Installation

  [user@localhost ~]$ sudo yum install ansible

_Note: You may need to add epel repo or download the download the rpm from http://fedoraproject.org/wiki/EPEL[epel]_

++ Exchange SSH key

If you need to generate the ssh key:
  [user@localhost ~]$ ssh-keygen -t rsa
  [user@localhost ~]$ ssh-copy-id -i ~/.ssh/id_rsa.pub user@hostname

Store the key to avoid retyping password:
  [user@localhost ~]$ ssh-agent bash
  [user@localhost ~]$ ssh-add ~/.ssh/id_rsa



=== Requirements
- *Host System*: Install Ansible [e.g. yum install ansible]
- *Gateway*: Download JBOSS Fuse 6.2.1 from the https://access.redhat.com/jbossnetwork/restricted/listSoftware.html?product=jboss.fuse&downloadType=distributions[Red Hat Customer Portal] and save it in the Downloads folder

=== Step 1 - Prepare the system using Ansible

We'll use the automation tool Ansible to remotely provision our Gateway system by installing required components.

 * Open a terminal and enter the following commands:
  
  [user@localhost ~]$ git clone -b Virtual-Lab-1 https://github.com/IshuVerma/Virtual_IoT_Gateway.git
 
 * Update the host file [Virtual-IoT-Gateway/Ansible/host] with IP address of the Gateway and place the public key of the host on the remote Gateway (Ansible uses ssh to communicate with remote system)

_Note: For the Gateway, we're using username = 'demo-user' and password = 'change12_me'. Please update the playbook with the  username/password for your Gateway_
 
 * Launch the Ansible playbook by entering the following commands:
  
  [user@localhost ~]$ cd Virtual_IoT_Gateway/Ansible
  [user@localhost ~]$ ansible-playbook BuildGW
  
*Let the Ansible run through the tasks in the playbook. Once Ansible is finished, we're ready to start work directly on the Gateway*
